---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    localprovisioner:
      replicas: 3
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: true
        basePath: "/var/openebs/local/hostpath"
      deviceClass:
        enabled: true
        name: openebs-device
        isDefaultClass: false
        basePath: "/var/openebs/local/device"
    loki-stack:
      enabled: true

