apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: helix-rabbit
  namespace: data-plane
spec:
  replicas: 3
  terminationGracePeriodSeconds: 60

  tls:
    secretName: rabbitmq-tls-secret

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_prometheus
      - rabbitmq_management
      - rabbitmq_mqtt
      - rabbitmq_stomp
      - rabbitmq_stream
      - rabbitmq_web_mqtt
      - rabbitmq_web_stomp
    
    
  persistence:
    storageClassName: openebs-hostpath
    storage: 10Gi

  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            priorityClassName: app-critical
