apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: helix-rabbit
  namespace: data-plane
spec:
  replicas: 3

  tls:
    secretName: rabbitmq-tls-secret

  resources:
    requests:
      cpu: 4
      memory: 10Gi
    limits:
      cpu: 4
      memory: 10Gi

  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
    
  persistence:
    storageClassName: openebs-hostpath
    storage: 10Gi

  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            priorityClassName: app-critical
