---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: data-plane
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 30m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clusterDomain: rabbitmq.${SECRET_DOMAIN}
    
    global:
      storageClass: openebs-hostpath

    clusterOperator:
      podLabels:
        sidecar.istio.io/inject: "false"
      metrics:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        podMonitor:
          enabled: true
    
    msgTopologyOperator:
      podLabels:
        sidecar.istio.io/inject: "false"
      metrics:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        podMonitor:
          enabled: true

    useCertManager: true