---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: data-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: openebs-hostpath

    clusterOperator:
      metrics:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        podmonitor: 
          enabled: true

    msgTopologyOperator:
      metrics:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
        podmonitor: 
          enabled: true
    