---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./network-policy/allow-rabbitmq-traffic.yaml
  - ./network-policy/allow-operator-traffic.yaml
  - ./network-policy/allow-inter-node-traffic.yaml

