apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ignore: 'true'
    kubernetes.io/metadata.name: istio-system