---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mysql
  namespace: data-plane
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 30m
  chart:
    spec:
      chart: mysql
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: openebs-hostpath
    
    auth:
      existingSecret: mysql-secret
      database: mysql

    primary:
      pdb:
        create: true
        minAvailable: 1

    secondary:
      pdb:
        create: true
        minAvailable: 1
    
    rbac:
      create: true
    
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      
      prometheusRule:
        enabled: true
      
      