---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/Ansible"
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/Kubernetes"
  PACKER_DIR: "{{.ROOT_DIR}}/Packer"
  # Files
  BOOTSTRAP_CONFIG_FILE: "{{.BOOTSTRAP_DIR}}/vars/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  MAKEJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/makejinja.toml"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_AGE_FILE: "{{.ROOT_DIR}}/.age.key"
  # Binaries
  PYTHON_BIN: python3
  # Python
  PYTHONDONTWRITEBYTECODE: "1"

env:
  KUBECONFIG: "./kubeconfig"

includes:
  ansible:
    aliases: ["ans", "ansible"]
    taskfile: ./.taskfiles/Ansible/Taskfile.yaml
  utilities:
    aliases: ["util"]
    taskfile: ./.taskfiles/Utilities/Taskfile.yaml
  repository:
    aliases: ["repo"]
    taskfile: ./.taskfiles/Repo/Taskfile.yaml
  kubernetes:
    aliases: ["k8s", "k0s", "k3s"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  terraform:
    aliases: ["tf"]
    taskfile: ./.taskfiles/Terraform/Taskfile.yaml
  sops: .taskfiles/Sops/Taskfile.yaml

tasks:

  default: task -l

  init:
    desc: Initialize configuration files
    cmds:
      - cp -n {{.BOOTSTRAP_CONFIG_FILE | replace ".yaml" ".sample.yaml"}} {{.BOOTSTRAP_CONFIG_FILE}}
      - cmd: echo === Configuration file copied ===
        silent: true
      - cmd: echo Proceed with updating the configuration files...
        silent: true
      - cmd: echo {{.BOOTSTRAP_CONFIG_FILE}}
        silent: true
    status:
      - test -f "{{.BOOTSTRAP_CONFIG_FILE}}"

  configure:
    desc: Configure repository from bootstrap vars
    prompt: Any conflicting config in the root kubernetes and ansible directories will be overwritten... continue?
    deps: ["utilities:direnv", "utilities:venv", "init"]
    cmds:
      - task: .template
      - task: sops:encrypt
      - task: terraform:encrypt
      - task: .validate

  .template:
    internal: true
    cmd: makejinja
    preconditions:
      - { msg: "Missing virtual environment", sh: "test -d {{.ROOT_DIR}}/.venv" }
      - { msg: "Missing Makejinja config file", sh: "test -f {{.MAKEJINJA_CONFIG_FILE}}" }
      - { msg: "Missing Makejinja plugin file", sh: "test -f {{.BOOTSTRAP_DIR}}/scripts/plugin.py" }
      - { msg: "Missing bootstrap config file", sh: "test -f {{.BOOTSTRAP_CONFIG_FILE}}" }

  .validate:
    internal: true
    cmds:
      - task: kubernetes:kubeconform

  remove-ssh:
    desc: Remove SSH keys
    cmds:
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.100"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.101"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.102"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.150"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.151"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.152"
      - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "192.168.86.153"
