---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vitess-cluster
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./Kubernetes/apps/data-plane/mysql/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: helix-ai-k8s-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
