---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: data-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: 0.15.9
      sourceRef:
        kind: HelmRepository
        name: ot-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    redisOperator:
      podLabels:
        sidecar.istio.io/inject: "true"
    replicas: 1
    serviceAccountName: redis-operator
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    
    service:
      name: webhook-service
      namespace: data-plane
    
    certificate:
      name: redis-operator
      secretName: redis-operator-tls
    
    issuer:
      type: selfsigned
      name: redis-operator-issuer
      email: ${SECRET_ACME_EMAIL}
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretName: letsencrypt-production
      solver:
        enabled: true
        ingressClass: internal

    