---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-cluster
  namespace: data-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 19.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      storageClass: openebs-hostpath

    auth: 
      enabled: true
      existingSecret: redis-cluster-secret
      password: redis-password
    
    master: 
      count: 3

    replica: 
      count: 5
      autoscaling:
        enabled: true
        minReplicas: 5
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
    
    sentinel: 
      enabled: true
      quorum: 2
      automateClusterRecovery: true
    
    pdb:
      create: true
      maxUnavailable: 1
    
    # TODO: add tls configuration for redis
    tls:
      enabled: false 
      existingSecret: helixaibot-com-production-tls

    metrics:
      serviceMonitor:
        enabled: true 
      
      podMonitor:
        enabled: true
      
      prometheusRule:
        enabled: true