---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"
  ANSIBLE_COLLECTIONS_PATH: "{{.ROOT_DIR}}/.venv/galaxy"
  ANSIBLE_ROLES_PATH: "{{.ROOT_DIR}}/.venv/galaxy/ansible_roles"
  ANSIBLE_VARS_ENABLED: "host_group_vars"
  ANSIBLE_LOCALHOST_WARNING: "False"
  ANSIBLE_INVENTORY_UNPARSED_WARNING: "False"

vars:
  ANSIBLE_LINT_FILE: "{{.ANSIBLE_DIR}}/.ansible-lint"
  ANSIBLE_INVENTORY_FILE: "{{.ANSIBLE_DIR}}/inventory/hosts.yaml"
  ANSIBLE_REQUIREMENTS_FILE: "{{.ANSIBLE_DIR}}/requirements.yaml"
  ANSIBLE_PIP_REQUIREMENTS_FILE: "{{.ANSIBLE_DIR}}/requirements.txt"


tasks:

  deps:
    desc: Set up Ansible dependencies
    deps: [":utilities:venv"]
    cmds:
      - .venv/bin/python3 -m pip install --upgrade --requirement "{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"
      - .venv/bin/ansible-galaxy install --role-file "{{.ANSIBLE_REQUIREMENTS_FILE}}" {{if eq .force "true"}}--force{{end}}
    preconditions:
      - { msg: "Missing Ansible requirements file", sh: "test -f {{.ANSIBLE_REQUIREMENTS_FILE}}" }
      - { msg: "Missing Pip requirements file", sh: "test -f {{.ANSIBLE_PIP_REQUIREMENTS_FILE}}" }
    sources:
      - "{{.ANSIBLE_REQUIREMENTS_FILE}}"
      - "{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"
    generates:
      - "{{.VIRTUAL_ENV}}/bin/ansible"
      - "{{.VIRTUAL_ENV}}/bin/ansible-galaxy"
    vars:
      force: '{{.force | default "true"}}'
