---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: "external.${SECRET-DOMAIN-1}"
      recordType: CNAME
      targets: ["${SECRET-CLOUDFLARE-TUNNEL-ID}.cfargotunnel.com"]
