---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dnsendpoint.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./Kubernetes/apps/network/cloudflared/app/configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
