apiVersion: ENC[AES256_GCM,data:mSA=,iv:m1QcMz/ZODdfnpNfUpnFDeX8RimN2G9X0jZdK2U2qZQ=,tag:0y7WJ3hDWFqexnUFaDkgbw==,type:str]
kind: ENC[AES256_GCM,data:lv99Pr2a,iv:sVcqotxj1gxiUg5Y2J5clX86I/hwUvW/CstevsvfLwg=,tag:9TnUu8BHBE76fhylXWHXdA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0ltSvH/hU7Kpdln7+hj4RLDS,iv:PhznkXyVkW4JTOI3aWfZOsA7/yrj4FmLmRJZQsKkEO4=,tag:V31L4n6I6rdSaf2KvHptvA==,type:str]
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2aVSNZtB/JLxVW9tPFf42z4A48TvfFpGt6GbRLS0DH5akq7B,iv:WevHSq2cuI3ObA8mbxR3FEbW8tpG2n3fecB3Sspwhl0=,tag:7VOVovL7atHNivq1WK6WAw==,type:str]
    credentials.json: ENC[AES256_GCM,data:V6doyNN42As1Pmmnt6zOWOu7RCJKZWoxnTnDUxXpwVVi9eIz4mKjmGBonu/JQra/zoTTwHfCoFl8a0gH/gw6iFz01N6PVP80s0xEiHirVcmGWdVS5MjqK7M+pD1rAhtg25GrvEtwOuAiWdTFNWh0Jxu46epXWqr4B5PwKQdJ6Qi8hpY9Fc0xFp6WZu2KN4ozquCxViX1dSSNK3b4ZEsxqYmTqIe8fO0MiFNle1laYw==,iv:GTMgNLPijQHUPe05IWQ5Z46Yl0qMnu26elq/uTljHcY=,tag:G13tu/lf8ZGpOWS6hjqh+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a2NFSHdjSEhjNDZhMWZn
            NFk4ZE01em80WWlQS3NyUFZxTlN1UVlDL0ZJCjRMQUZ5Q0QwNnFkaTUvZS9kUlNB
            K2VYa2tIdjJPZXBiU3drVlZwVFNJK0kKLS0tIEh4ajhuaGEyQ0w5RWZnSW5BNDlp
            MFVSbU43Yk5ZcXJxMUE1VkhEazFJMkUKeL7N9sKN9rAwe9tj0EmbuIIWF9J/BrUO
            OE1TGGlIdTeRjA4myOyiWXHpaHcJN3b41xc2pxWEE8buWr7ZFj9X9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T05:23:50Z"
    mac: ENC[AES256_GCM,data:uUYRWmEjcWWMYLJ9B5tK53lPhiKSrjFPCMBq4bh481NUDBJza8VeM2+5GnZjsjmKz8JIT1fSBi/XyLHQWtg7GnQxrXFK+1w/7s3T7ojrG93DqSTiFKUHbetLlkbKMimHwNTvJn5JxN3WIzaXy11d8k1o7Ebv+vmEw2dHsnWMV2g=,iv:MwABuzUcKBMy1fJg7EiWmXpvV+5gymihcVsQtODB9CE=,tag:TueJcC2nP8V8parvUnfZPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
