---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      version: "7.3.7"
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    autoscaling:
      enabled: true
      maxReplicas: 5
      minReplicas: 1
      targetCPUUtilizationPercentage: 60

    serviceMonitor:
      enabled: true

    ingress:
      enabled: true
      ingreessClassName: external
      hosts:
        - grafana.${SECRET_DOMAIN}
      tls:
        - secretName: helixaibot-com-production-tls
          hosts:
            - grafana.${SECRET_DOMAIN}

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    admin:
      existingSecret: grafana-admin-credentials
      userKey: adminUser
      passwordKey: adminPassword

    