---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    admin: 
      existingSecret: grafana-admin-secret
      passwordKey: admin-password
      userKey: admin-user
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: openebs-hostpath
    autoscaling:
      enabled: true
      maxReplicas: 5
      minReplicas: 2
      targetCPU: '60'
    ingress:
      enabled: true
      ingressClassName: external
      hosts:
        - grafana.${SECRET_DOMAIN}
      tls:
        - secretName: helixaibot-com-staging-tls
          hosts:
            - grafana.${SECRET_DOMAIN}
    
    plugins:
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
      - digrich-bubblechart-panel
      - https://grafana.com/api/plugins/marcusolsson-json-datasource/versions/1.3.2/download;marcusolsson-json-datasource
    
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: https://prometheus.${SECRET_DOMAIN}
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki.monitoring.svc.cluster.local
          - name: Tempo
            type: tempo
            access: proxy
            orgId: 1
            url: http://tempo.monitoring.svc.cluster.local