---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
    admin: 
      existingSecret: grafana-admin-secret
      passwordKey: admin-password
      userKey: admin-user
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: openebs-hostpath
    autoscaling:
      enabled: true
      maxReplicas: 6
      minReplicas: 1
      targetCPU: "60"
    ingress:
      enabled: true
      ingressClassName: external
      hosts:
        - grafana.${SECRET_DOMAIN}
      tls:
        - secretName: helixaibot-com-staging-tls
          hosts:
            - grafana.${SECRET_DOMAIN}
    
    plugins:
      - https://grafana.com/api/plugins/marcusolsson-json-datasource/versions/1.3.2/download;marcusolsson-json-datasource
    
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          
          - name: "flux"
            apiVersion: 1
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/flux
    
    dashboards: 
      default:
        Prometheus-stats:
          url: https://grafana.com/api/dashboards/2
          name: Prometheus Stats
          orgId: 1

    dashboardConfigMaps:
      flux: "flux-grafana-dashboards"


      
    
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: https://prometheus.${SECRET_DOMAIN}
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki.monitoring.svc.cluster.local
          - name: Tempo
            type: tempo
            access: proxy
            orgId: 1
            url: http://tempo.monitoring.svc.cluster.local