---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
  interval: 30m
  chart:
    spec:
      version: "7.3.7"
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    autoscaling:
      enabled: true
      maxReplicas: 5
      minReplicas: 1
      targetCPUUtilizationPercentage: 60

    serviceMonitor:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - grafana.${SECRET_DOMAIN}
      tls:
        - secretName: helixaibot-com-production-tls
          secretNamespace: network
          hosts:
            - grafana.${SECRET_DOMAIN}

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    admin:
      existingSecret: grafana-admin-credentials
      userKey: adminUser
      passwordKey: adminPassword

    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: openebs-hostpath

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: flux-system
            orgId: 1
            folder: 'flux'
            type: file
            options:
              path: /var/lib/grafana/dashboards/flux-system
          
          - name: prometheus
            orgId: 1
            folder: 'prometheus'
            type: file
            options:
              path: /var/lib/grafana/dashboards/prometheus
          
          - name: loki
            orgId: 1
            folder: 'loki'
            type: file
            options:
              path: /var/lib/grafana/dashboards/loki
          
          - name: cilium
            orgId: 1
            folder: 'cilium'
            type: file
            options:
              path: /var/lib/grafana/dashboards/cilium
    
    dashboardsConfigMaps:
      flux-system: flux-dashboards
      prometheus: prometheus-dashboards
      loki: loki-dashboards
      cilium: cilium-monitoring-dashboards

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            orgId: 1
            isDefault: true
            url: http://prometheus-server.monitoring.svc.cluster.local

          - name: Kube State Metrics
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus-kube-state-metrics.monitoring.svc.cluster.local

          - name: Node Exporter
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus-node-exporter.monitoring.svc.cluster.local

          - name: Alertmanager
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus-alertmanager.monitoring.svc.cluster.local

          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://grafana-loki.monitoring.svc.cluster.local
          
          - name: Mimir 
            uid: prom 
            type: prometheus
            url: http://grafana-mimir-nginx.monitoring.svc.cluster.local

          - name: Tempo
            type: tempo
            orgId: 1
            url: http://grafana-tempo-query-frontend.monitoring.svc.cluster.local
            jsonData:
              tracesToLogsV2:
                datasourceUid: loki
              lokiSearch:
                datasourceUid: loki
              tracesToMetrics:
                datasourceUid: prom
              serviceMap:
                datasourceUid: prom