apiVersion: ENC[AES256_GCM,data:yOU=,iv:lG3jpQeWQMnWa2VUDDS63j9nnibgktwpb+GBLnUuwQA=,tag:D+nINUiDOqzC/8O4cCb08Q==,type:str]
kind: ENC[AES256_GCM,data:Hjv0P9dW,iv:H6voTLqRKN0TWinm8bf80cPM8iEASs6O5b7iNETUR+Q=,tag:BECW+OIdSWoNK/CFXwH1TQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wWDNvHDY+zrlFzQYJCCGNkVngBW06egf8Q==,iv:Pq2rJHIPHhuXeBUGqEiquCrOQA2JlphyNNUFI7xGyQ8=,tag:NeJZnuLHtuswwHiFXj+e/A==,type:str]
    namespace: ENC[AES256_GCM,data:FS0OMcoSvOnkdA==,iv:9Q6bIEgqqVqhsCOP4LoEy6FFJjo49iEhK+T19TP8NgE=,tag:av0+wooDWTzlIc7T8CBb5Q==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:Bu96lgnZr9gR7w==,iv:jVFMoHu47W3L1j8TgtHBE95H7FRezy8GtbNpgN9f9CM=,tag:kJyVuHeAZzYEJ0vkmOEgUQ==,type:str]
    admin-password: ENC[AES256_GCM,data:VPIwcGRphh1Es41OlaE=,iv:DK7ssY+hcjgWK6YHooyfVrZzcTjWVNZ3hGjFE0QbfTM=,tag:crX1aAM2fGPYtn/i1Jvvcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNEpnKzhKSVpsVDJ0T2Fj
            Ym5XcXowMzM3YldzdCtlZkxOUmxQZmNkbVJRCkZiTW90Q2plbDlWOUQvL2luQ0hK
            Y3U5RkFYUnFSOVYxclZmT09xWkI1dkkKLS0tIGlDSkovZVZIcGtiRDZQWHNBWk05
            bUNUQkgyNUw4QVZibHIrYVlEWGQzdDAK9awq3pI+DBEjUZ7bofUqM8VPOdrVTUcd
            PZAa4RcQdCkgrmsAT5a8dsvuZv/wqnuiPrKPrRuCEie82f3gtqFdyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-19T00:19:03Z"
    mac: ENC[AES256_GCM,data:kVzpr2VFeUx2NJSVKlCMI15JyyHjw6+92jxQiFaXKrguFzD8W2+Sd8OPFGQVMlKdAjeIDk9DSmDFCixEjtLXM4GeAz3TzKt8EQR5Gv5R1eZRPgy3IFmpHIHP30A1gpJGfTcEXkL5GpG7X3kk3dxHis5qtHuiw6+F+CzPnuxll6k=,iv:aYJJ3xh7IEyuM7mWGqUN3+Cu3FPLQLdVv0TCawL9dZw=,tag:/4lxn7aRFebIQqeIuqixfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
