---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rancher
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./Kubernetes/apps/cattle-system/rancher/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: helix-ai-k8s-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
