
kubernetes:
  children:
    master:
      hosts:
        "k8s-master-1-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.100"
        "k8s-master-2-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.101"
        "k8s-master-3-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.102"

    worker:
      hosts:
        "k8s-worker-1-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.150"
        "k8s-worker-2-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.151"
        "k8s-worker-3-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.152"
        "k8s-worker-4-production":
          ansible_user: "sinless777"
          ansible_host: "192.168.86.153"

# The Pihole group contains all the hosts that need to run Pihole
pihole:
  hosts:
    pihole-1:
      ansible_user: "sinless777"
      ansible_host: "192.168.86.80"
    pihole-2:
      ansible_user: "sinless777"
      ansible_host: "192.168.86.81"
