apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: system-app-critical
value: 2000002000
globalDefault: false
description: "This priority class should be used for system critical applications"