---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubedb
  namespace: data-plane
spec:
  interval: 30m
  chart:
    spec:
      chart: kubedb
      version: v2024.3.16
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      licenseSecretName: kubedb-license