apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 7.10.0
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1
  nodeSets:
  - name: elastic-01
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
  - name: elastic-02
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
  - name: elastic-03
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data