apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: helix-ai
spec:
  version: "8.12.2"
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1
  nodeSets:
    - name: masters
      count: 3
      config:
        # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
        # node.master: true
        node.roles: ["master"]
        xpack.ml.enabled: true
    - name: data
      count: 7
      config:
        # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
        # node.master: false
        # node.data: true
        # node.ingest: true
        # node.ml: true
        # node.transform: true
        node.roles: ["data", "ingest", "ml", "transform"]