---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    rbac: 
      create: true

    ingester:
      autoscaling:
        enabled: true
        maxReplicas: 5
        minReplicas: 1
        targetCPUUtilizationPercentage: 60
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      persistence: 
        enabled: true
        storageClassName: openebs-hostpath
    
    distributor:
      autoscaling:
        enabled: true
        maxReplicas: 5
        minReplicas: 1
        targetCPUUtilizationPercentage: 60
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    querier:
      autoscaling:
        enabled: true
        maxReplicas: 5
        minReplicas: 1
        targetCPUUtilizationPercentage: 60
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    memcached:
      enabled: true

    memcachedExporter:
      enabled: true
    
    metaMonitoring:
      serviceMonitor:
        enabled: true

    prometheusRule:
      enabled: true
    
    minio:
      enabled: true
      persistence:
        enabled: true
        storageClassName: openebs-hostpath