---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    serviceMonitor:
      enabled: true
      interval: 30s
    tempoQuery:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - query.tempo.${SECRET_DOMAIN}
        tls:
          - hosts:
              - query.tempo.${SECRET_DOMAIN}