apiVersion: ENC[AES256_GCM,data:y14=,iv:2sd+FidDcEGTZUnGGEa6fdrjTwPow1tni1Pv1Tl1onY=,tag:7QhM/DR4Irhih3099/EWMw==,type:str]
kind: ENC[AES256_GCM,data:bD0aIhZ2,iv:NlcYXWPJbkGGkFOUHBXWJ3SIVoO3dOD7C1ksT1R6eaU=,tag:lYtyJMKFmng+inviM2vg2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H4ni/nxp7gzj5rVR/NelKYIiRA==,iv:0E7xwHWBICMmVYpi4flGnwjcC1NFSRK45pqePO+dnV4=,tag:WsJNhFs7h06qrewzlDeoTw==,type:str]
    namespace: ENC[AES256_GCM,data:RLhRWCsSKh72VTAW,iv:FD+oiWLQYHzUADnPP0NKiClprwKt3GHHlfGr6S8HF0A=,tag:CkbM0sy1edT1O4T9e3XUbA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:f1mmxBqExyQRU6uRYuYijBcT2CdiwdHQpsA9XG+Z+op/jpUR0BvbwQ==,iv:unOmfGLYQQpsH9u+8I4RN8Jsz2XHGU//lXH9TphaILg=,tag:ZOkkUkqL1FsJwtWyUiPCKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUFI1ZzhQWU95RjdxeU5a
            dUovODR3aGF3b3VQcVdBcDk1T0xQNHR5Zkg4Ci9iTG9uOWRsSHhZZ0VZanVYVHFH
            VWxUTEExWXlka0JtQjViZVI4Tk03R2sKLS0tIFdwMXRBbjRiT3Z0VGVYY25UVkhz
            ejRHOGsxeUc0SXdQV2tvYzVHRjNMVmMKZhM1i2LVaq8Ij7fr5FQdJGkjb/+ZYg3/
            KxAIa/9LGJ+mzGeBSvNaNwlKIQQnqxZFq4edPOLY4+JG8mZ0LouXbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T23:12:33Z"
    mac: ENC[AES256_GCM,data:7QkPQQroHKYxp+QfqTQx0xewtsfZPuNPEb2NG8n4/OzaXZGn7pTpUoWy2lCKC1dLFKL8jbasFhOaIXFRbgMmH3g2X5xwzbYRe9/PbTesr3ZSXqjUmSUAZ6QHZ/YKerBdIBFcaW23XjiKEK0IEf2jN9E1aXkNrFBqPKx83/kvYrU=,iv:PmY5y5urJ2p+r5DfyUSshVxpcontO0wit+sBJCRLJdU=,tag:aFzYcdDBNd7mk8C1vqWkwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
