apiVersion: ENC[AES256_GCM,data:VWk=,iv:HgJU4HXmR4AxsLrOlpeoThE8AXK9psstaeDetArLWdQ=,tag:CytV2euG84jgV3yN7GPxuA==,type:str]
kind: ENC[AES256_GCM,data:cDKEpbUY,iv:ty1U7wFfK6UCpYi2Jy16YHsVs9SfuIX/2UiETDT+KXs=,tag:sjy059qnQfUa9jBJsZnMIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gmr1sGZ/ayCMzJIW4QVYAXYIWg==,iv:9MG8R2jjGBFNI+oFV3OyL0CJg7FmUMjWUE5yILlgN5U=,tag:TbWM9UJDquaCQHlky3v+3Q==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:ktPRR0YkW4LoYEezQW1eTgPH6ofxPEY71IdRDccqVG9zxJS3tFqwUw==,iv:xLud6mWTkA/alaKecWGSr54GgXyb7nfpYZF5FBIgpTU=,tag:mn9ZD6L6Ke1b+2hEuI9CKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age195rdta0e2jx49x3djpcchyc2gdslv3kdedsnzeu23xmtwremk93qpwvseu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT2VwR1ZiSkcvM1lQSjRu
            M1J4K2l0K2h5di93ZWRacnZjUmwzSUdoN0VrCnRZSWllRzF2d3Z5NFczbnpOSU81
            ckh3cTRqTGlZdFhyWTVMNFZTS2tYYVEKLS0tIFhiOGhzRUVWTmM0anVWTWhxTGl2
            RitGU3ZJemR6Q3I2Q3pkUzNnVjNCdkUKT51uM2P+pbsU8EdcfK9j9MZ3b2T98f43
            HrGXcyhTbfLzfNEW8CVSXavDwGLqYVbKJ9FB0csnpHTEgobCYxl1fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T02:51:31Z"
    mac: ENC[AES256_GCM,data:yYifdofpL04xOA8rRvf8q4SOMs5Ux3gmd4zNfboOmTdrZsccLYLiMFV4+fXGKXD36ABZSjMrFntBo8u5xwSSsywjMuzL6EBEOotFE7pcz+qdP4/cdhVbDstqEOtk9EooIr6tpr5nwH/lC8FYQSaIf/TVfNbWdMclJ51FUAkfm6I=,iv:YTcL0wwAIbnmqunz031kFa+4dZ3NNppOoY2tPjp03/A=,tag:sH/yYpAwTbgS/NkHmpenxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
