apiVersion: ENC[AES256_GCM,data:oEg=,iv:vit84KzITzvWzr4zajWE11veK9I0XdGoj+yII+7m6ls=,tag:CA/KY/znjs9LHUZnBEe+6Q==,type:str]
kind: ENC[AES256_GCM,data:YrnUe0cf,iv:Hz+fZDd32IWRZVeHBFQiEvM/RGGX6TYNyhqWNXi4rsA=,tag:9+ul1HWoIBNg/cbNr9mAIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+XAc5xG8yjviR9cBqpzRR+LKHA==,iv:4whDk8enjShEouXWCuBeXFTYhOMJnuvopJqSr5/nEA0=,tag:YUbrogU+4Km9MJTy+f7WcQ==,type:str]
    namespace: ENC[AES256_GCM,data:jM41IiLqI0nMi0yH,iv:ePIJajzPs8/cKeqt3Swyn/XfUWusl7pvDv8g3LR2rys=,tag:s/h1iedGCxv2y39EGKHm9w==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:n/NyyKIcHuyj7y0a3sM+lsh3KiFgqwqYMCecFJhyoquoVUYahQx0Wg==,iv:/6mDUktXBxkKMtw1w7/c+2J4xQDw/wwkQzWS4603mpo=,tag:rc6LEcvkR+4B6T7gAhHLJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNGp5VTdzUENPVmt3NEFh
            OUh1RDF0RWVsaFRjOUZlMGVXdldRaWxMbjJFCkF1VnBwcUNyQ1pzZDFpMDUraHd0
            M3Yxc2taM3dQWkpKbmJQaC9mVWdwUzAKLS0tICtpK1lETkhKTzBmb2N3blc0Ni91
            dStnZjlJbnpQUjdUTUF2ZUtCUWtqUWsK4+ceUMysljKRzMSeGA4yohcE0unTim6D
            QndaIPjUa7suMk8sbFGa83Fg/1CBkQkM4+HFfkvqV6xr47pETXOboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T22:29:56Z"
    mac: ENC[AES256_GCM,data:dl2lHkP8GIjoja1YAv8/S6JW3PycLZPAFzGq14j9zxTpfOFzur6LJwLfjOdjLr0ErWzUysRlDiLlA9vE92qLyaZGxkSUPYPjX7ivfKltxQUoaJIec5q3W4HL5LxWeVRsPYcmuhEsaJoosRIlICoJ2HH8iMgaRQKQVw6d5XtI/JM=,iv:yPaSiuIrTHZ7lppM2J3JVd+Yk5CjmieKOWch3gT4c5M=,tag:M52J2TasIQ+YNoBeH/bD+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
