apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      version: "25.x.x"
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
        target:
          kind: PrometheusRule
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations: 
          kubernetes.io/ingress.class: internal
          kubernetes.io/tls-acme: 'true'
        hosts:
          - alertmanager.${SECRET_DOMAIN}
        tls:
          - secretName: helixaibot-com-production-tls
            hosts:
              - alertmanager.${SECRET_DOMAIN}
      persistantVolume:
        storageClass: openebs-hostpath
    ingress:
      enabled: true
      ingressClassName: internal
      annotations: 
        kubernetes.io/ingress.class: internal
        kubernetes.io/tls-acme: 'true'
      hosts:
        - prometheus.${SECRET_DOMAIN}
      tls:
        - secretName: helixaibot-com-production-tls
          hosts:
            - prometheus.${SECRET_DOMAIN}
    
    server:
      PersistentVolume:
        storageClass: openebs-hostpath