apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring

spec:
  interval: 1h
  chart:
    spec:
      version: "25.17.0"
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    labels:
        sidecar.istio.io/inject: "true"
    server:
      ingress:
        enabled: true
        hosts:
          - prometheus.${SECRET_DOMAIN}
        tls:
          - secretName: helixaibot-com-production-tls
            hosts:
              - prometheus.${SECRET_DOMAIN}
    
    alertmanager:
      enabled: true
      replicaCount: 2
      ingress:
        enabled: true
        hosts:
          - host: alertmanager.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: helixaibot-com-production-tls
            hosts:
              - alertmanager.${SECRET_DOMAIN}
    
    kubeStateMetrics:
      enabled: true
      autosharding:
        enabled: true
      replicas: 4
      prometheus:
        monitor:
          enabled: true
        podMonitor:
          enabled: true

    nodeExporter:
      enabled: true
      prometheus:
        monitor:
          enabled: true
        podMonitor:
          enabled: true  
    