apiVersion: ENC[AES256_GCM,data:aco=,iv:/C8cyumEo+56HDpdzT7jYoujwu45Eml15pNZqK+ghVY=,tag:is3ZHfw/0VjNn79MbgCq5Q==,type:str]
kind: ENC[AES256_GCM,data:Jc7a3Kyg,iv:3ZVk4qD6oyEulQy3Dp4JbafwcrZMWUXVKizpEF3+MkI=,tag:CvmxGDxnESxvPabFnCxmug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wy1Mtad/r+HtoIzuig==,iv:xu4H9SV/T0JylOk4HmHdsGf3WhswZE7yFIxlcEgQlnQ=,tag:cVAGOW+z/6M1C1dhPSTJ8A==,type:str]
    namespace: ENC[AES256_GCM,data:j6NZXM4N5G3dbw==,iv:SUscLtyjheNjcYTX1yY/p+y1OWu7Nu0LZSGLXYFnXYE=,tag:9OlkYIxj9ier6km+2bvlSQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:y8GYdqYx1uLvRg==,iv:TyMK4+br8N1/ugyy2ju7pzwoIcePT8FhXpyvTd2nafc=,tag:pTFApN+yg/G/NC14oio4Fw==,type:str]
    admin-password: ENC[AES256_GCM,data:BcmC6gOic9ITegs26ns=,iv:7usL+Urzpfmbfwt3npbXxKSJ/MZhehoxEn+UnroV0g0=,tag:tNG6WDQCZsMWrg55W/cjhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeUxuajlsZmJ3RmYyZG9m
            VjNSU0JBUkVCU0c4K242YjNKTndUOHI1c1NjCko5cVZ2NmtTcFM5Zlp5a0RKZ3p6
            RkQzZStIQWR1Ui9LZmZpV05yNVBYMTgKLS0tIDB3aWxYS2MydWVkaVZUWnViNHVW
            WkEzNkVRemlkMGpIVHVXa2V5ZHJtSjQKPihcxxDPlkgwNjUmJHXdoBGmg4j5Tw49
            VIc3jWfH1TOyUwMRDNe73ArixXwLoAooD/3/hCX2nKuDagegvDu3fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T07:02:37Z"
    mac: ENC[AES256_GCM,data:UbU4jHV6m66IpZfzakqQYxajPU9ZMZJtn5uaUDY0mVSTlsh0aJSK5XQ/V0RmfsBfr1ifttXDQNQLLT7Epp10qTrYmPN+W7xWjOt1gjUjSLMXp7P7PpjiQ/Qa1AuO/7FaAuom1TilqAeNwsZlFLpnoK9F+zIO8fo2FaqsySVNiok=,iv:xIs6jjQKyrcXQP/0tHRxY1UtmqzRQNSRuogeacQnO54=,tag:etEau4F2lBmqvKIbxRYPug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
