apiVersion: ENC[AES256_GCM,data:aco=,iv:/C8cyumEo+56HDpdzT7jYoujwu45Eml15pNZqK+ghVY=,tag:is3ZHfw/0VjNn79MbgCq5Q==,type:str]
kind: ENC[AES256_GCM,data:Jc7a3Kyg,iv:3ZVk4qD6oyEulQy3Dp4JbafwcrZMWUXVKizpEF3+MkI=,tag:CvmxGDxnESxvPabFnCxmug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wy1Mtad/r+HtoIzuig==,iv:xu4H9SV/T0JylOk4HmHdsGf3WhswZE7yFIxlcEgQlnQ=,tag:cVAGOW+z/6M1C1dhPSTJ8A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:hz58XoExh4eaJw==,iv:LI5Nh64IJdNLber2/txBBaXghdgVteLNaBrc/24SNgU=,tag:GwSFAgKHEc7P8WAhBG3IxQ==,type:str]
    password: ENC[AES256_GCM,data:I9llq454tb3n1qY+BLo=,iv:zahw5M/vWttsjeZQo5tH1t897p2Cm7aY6/eeYnYO2l4=,tag:8G+5kt/zujaw3+D45nbVLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeUxuajlsZmJ3RmYyZG9m
            VjNSU0JBUkVCU0c4K242YjNKTndUOHI1c1NjCko5cVZ2NmtTcFM5Zlp5a0RKZ3p6
            RkQzZStIQWR1Ui9LZmZpV05yNVBYMTgKLS0tIDB3aWxYS2MydWVkaVZUWnViNHVW
            WkEzNkVRemlkMGpIVHVXa2V5ZHJtSjQKPihcxxDPlkgwNjUmJHXdoBGmg4j5Tw49
            VIc3jWfH1TOyUwMRDNe73ArixXwLoAooD/3/hCX2nKuDagegvDu3fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T06:52:29Z"
    mac: ENC[AES256_GCM,data:6sO2GBEoF+UGJ2vOvqmp+hBZQuzGSuChJCBXY21xSrlM3ZZ7+NFmCixVRbaEze7JZ0os/Qrr9jXPvShesbZ67Ocgwg/AesKhAtV5r3yabsQAeMylRXZ1Xgx9vdJmED8E4ijF48lJ6Z54ao2W5NsMi03GfKtIdBwSID3ifYoT44k=,iv:Z40UigCzRwBQn/3DYcJj5BHugo6Ua8hXG/s3dxInGcM=,tag:rhORQ5TH8zUCILJyEZGwug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
