---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
  namespace: openebs-system
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    namespace:
      labels:
        # Enforce Pod Security Standards with Namespace Labels
        # https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/
        - key: pod-security.kubernetes.io/enforce
          value: privileged
        - key: pod-security.kubernetes.io/enforce-version
          value: latest
        - key: pod-security.kubernetes.io/audit
          value: privileged
        - key: pod-security.kubernetes.io/audit-version
          value: latest
        - key: pod-security.kubernetes.io/warn
          value: privileged
        - key: pod-security.kubernetes.io/warn-version
          value: latest

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: cloud-credentials
            mountPath: /credentials
            readOnly: true
      - name: openebs-plugin
        image: openebs/velero-plugin:1.9.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: localpv-provisioner
            mountPath: /var/openebs/local
            readOnly: true

    metrics:
      enabled: true
      # Pod annotations for Prometheus
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"

      serviceMonitor:
        autodetect: true
        enabled: true

      nodeAgentPodMonitor:
        autodetect: true
        enabled: true
        spec:
          - alert: VeleroBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
            expr: |-
              velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
            for: 15m
            labels:
              severity: warning
          - alert: VeleroBackupFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
            expr: |-
              velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
            for: 15m
            labels:
              severity: warning
    
    # This job upgrades the CRDs.
    upgradeCRDs: true

    # This job is meant primarily for cleaning up CRDs on CI systems.
    # Using this on production systems, especially those that have multiple releases of Velero, will be destructive.
    cleanUpCRDs: false

    ##
    ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
    ## and additional server settings.
    ##
    configuration:
      backupStorageLocation:
        - name: Amazon AWS 
          provider: aws
          bucket: velero-b0ackup-helix
          validationFrequency: 30m
          credential:
            existingSecret: velero-credentials