apiVersion: ENC[AES256_GCM,data:5N4=,iv:i6sXWYhg9gORAPwuXfcAfZVDWKfM2DxyeQ4svJRY8TY=,tag:0f4EgR8fEkUe6z7i9tZ7cQ==,type:str]
kind: ENC[AES256_GCM,data:Hqg3Tw1i,iv:hOZrTPNlZ45BrxPHKSDuK5YoPD8v4QLj/s0LDUZbVvk=,tag:RTns8uBVZQT5/8nwtT0hFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nttnJobH3bTVKF2yb8PbGAh1,iv:jqk9gLNVjjPGxuYXQsvpSbVZY2Aui63ZuwuBGYo00jM=,tag:pb8iF0+3p4E3FweIb5d+Pw==,type:str]
    namespace: ENC[AES256_GCM,data:/vwxcFcWNzvXWFf2MMo=,iv:JpwAx+aq2osDwrtXwqMEswly41ifHImUa7t5QXlq6Wk=,tag:u6qCe637nA+yxjJCqmH48Q==,type:str]
type: ENC[AES256_GCM,data:/vPFvaWk,iv:28gPA2JwQymXIwTUJMjGockZTp+Dl4WyGdvVewtMRAI=,tag:DPTx8Imxw5lDRp+S4OyVHg==,type:str]
stringData:
    aws: ENC[AES256_GCM,data:v/k8fxMkYrvmhNoRU7iMJxeHK9I1T/CPNg2lIkMaqh+c4S6mFDWMoJZwma72DtD19mOeKO9OLrVk6LT5WELKGoJXfHjU98Lh8JZcT21Gmhd5efEKcoa46atzxDF8icgGyvDfUxJ5lt28FCdSgLF1S46BcA==,iv:9IxrKQkAuGmzRtAXSkKZa0nSql8LSRmrIyZeEL0Pdsc=,tag:/Tjl8qtJV+dCXvzIpgVixg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY3V5ZE93ZEpCMzc0aHFE
            NmlKNmNUVW5KL3hua3lWblY0TU1NbXhNTGtvCkNaRDRkNE1INUl1d3ZDVGFjS3oy
            a3VxTEg3VTRrcU1ONHFTenhHZzdOMVEKLS0tIG5MS1k0WjN2TWxWVzhkcWUzTWM4
            TEhaOC92WDlublJrVm1idjZ0UUpVaUkK1xne1KlfTNsYfu5Tji0+feqM0NVIGuY5
            g80SZnWF/sPnnPRmBWOzv6DdxG9JX2dWaWOXYolddUbOUsZHe5TMYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T02:24:27Z"
    mac: ENC[AES256_GCM,data:FJj96r5vgWq6nn19do/i/L5OqtIyXdCvOPCLu5nMLCqpQMWu5/ikuQnkMJ095L6vNfoxsM2ZHqgLWjLHZxZVtWF39pS/Lla3L2SWIgdnrR3Wu0Yladwogvqv+w6lsATvcD75EM+q9x2IIEHAIbhHpBo7Ca/1hD0OWNIRYIi1t+k=,iv:0xaU4NuI7bh+8e44UNb350mzGppQ912Op9u5PDhvnYk=,tag:T4hH5ptTbFr4SfK7Nj7Rgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
