---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET-DOMAIN-1/./-}-production"
spec:
  secretName: "${SECRET-DOMAIN-1/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET-DOMAIN-1}"
  dnsNames:
    - "${SECRET-DOMAIN-1}"
    - "*.${SECRET-DOMAIN-1}"
