---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_1/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN_1/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_1}"
  dnsNames:
    - "${SECRET_DOMAIN_1}"
    - "*.${SECRET_DOMAIN_1}"
