---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN1/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN1/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN1}"
  dnsNames:
    - "${SECRET_DOMAIN1}"
    - "*.${SECRET_DOMAIN1}"
