---
- name: Cluster Installation
  hosts: production
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: check if production cluster
      ansible.builtin.debug:
        msg: "Production Cluster: {{ production_cluster }}"
      
    - name: install production cluster
      when: production_cluster == true
      block:
        - name: Check if cluster is installed
          check_mode: false
          ansible.builtin.stat:
            path: /etc/rancher/k3s/config.yaml
          register: k3s_installed

        - name: Ignore manifests templates and urls if the cluster is already installed
          when: k3s_installed.stat.exists
          ansible.builtin.set_fact:
            k3s_server_manifests_templates: []
            k3s_server_manifests_urls: []

        - name: Prevent downgrades
          when: k3s_installed.stat.exists
          ansible.builtin.include_tasks: tasks/version-check.yaml

        - name: Install Kubernetes
          ansible.builtin.include_role:
            name: xanmanning.k3s
            public: true
          vars:
            k3s_state: installed
            k3s_release_version: v1.29.1+k3s2

        - name: Kubeconfig
          ansible.builtin.include_tasks: tasks/kubeconfig.yaml

       
