---
- name: Cluster Installation
  hosts: production
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: install production cluster
      when: production_cluster == true
      block:
        - name: group hosts for production
          add_host:
            name: "{{ item }}"
            groups: production
          with_items: "{{ groups['production'] }}"

        - name: Print all variables/facts known for a host
          debug:
            var: hostvars[inventory_hostname] 

