---
- name: Cluster Installation
  hosts: production
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Filter hosts with "production" in the name
      set_fact:
        production_hosts: "{{ ansible_play_hosts | select('search', 'production') | list }}"

    - name: Print production hosts
      when: ansible_hostname == 'k8s-master-1-production'
      debug:
        var: production_hosts

    