---
- name: Cluster Installation
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  vars:
    production_hosts: []
  tasks:  
    - name: Filter hosts with "production" in the name
      set_fact:
        production_hosts: "{{ ansible_play_hosts | select('search', 'production') | list }}"

    - name: Print production hosts
      when: ansible_hostname == "k8s-master-1-production"
      debug:
        var: production_hosts
      
    - name: Set ansible_play_hosts to empty list
      ansible.builtin.set_fact:
        ansible_play_hosts: []

    - name: Reset Ansible play hosts
      ansible.builtin.set_fact:
        ansible_play_hosts: production_hosts

    - name: print ansible_play_hosts
      when: ansible_hostname == "k8s-master-1-production"
      debug:
        var: ansible_play_hosts