apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      name: helix
      logLevel: info
      logJSON: false
      domain: ${SECRET_DOMAIN}
      image: docker.mirror.hashicorp.services/hashicorppreview/consul:1.18.0
      datacenter: Helix-Ai-DC1
      peering:
        enabled: true
      tls:
        enabled: true
        caCert:
          secretName: helixaibot-com-production-tls
          secretKey: tls.crt
        caKey:
          secretName: helixaibot-com-production-tls
          secretKey: tls.key

    server:
      replicas: 5
      bootstrapExpect: 5
      storageClass: openebs-hostpath
      storage: 10Gi

    connectInject:
      enabled: true
      default: true
    
    meshGateway:
      enabled: true
      replicas: 1
    
    controller:
      enabled: true

    ui:
      enabled: true
      service:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        pathType: Prefix
        hosts:
          - host: consul.${SECRET_DOMAIN}
            paths:
              - /
        tls:
          - hosts:
              - consul.${SECRET_DOMAIN}
            secretName: helixaibot-com-production-tls
