---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      # The main enabled/disabled setting.
      # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
      enabled: true
      # The prefix used for all resources created in the Helm chart.
      name: consul
      domain: "${SECRET_DOMAIN}"
      # The consul image version.
      image: hashicorp/consul:1.16.0
      # The name of the datacenter that the agents should register as.
      datacenter: "Helix-Ai-DC1"
      # Controls whether pod security policies are created for the Consul components
      # created by this chart. Refer to https://kubernetes.io/docs/concepts/policy/pod-security-policy/.
      enablePodSecurityPolicies: true
      # Enables ACLs across the cluster to secure access to data and APIs.
      acls:
        enabled: false
        # If true, automatically manage ACL tokens and policies for all Consul components.
        manageSystemACLs: true
      # Exposes Prometheus metrics for the Consul service mesh and sidecars.
      metrics:
        enabled: true
        # Enables Consul servers and clients metrics.
        enableAgentMetrics: true
        # Configures the retention time for metrics in Consul servers and clients.
        agentMetricsRetentionTime: "1m"
      # One of "debug", "info", "warn", or "error".
      logLevel: "info"
      logJSON: false
      tls: 
        caCert:
          secretName: helixaibot-com-production-tls
          secretKey: tls.crt
        caKey:
          secretName: helixaibot-com-production-tls
          secretKey: tls.key

    server: 
      replicas: 3
      bootstrapExpect: 3
      storage: 2Gi
      storageClass: "openebs-hostpath"

      exposeService:
        enabled: true
        type: "LoadBalancer"
    
    externalServers:
      enabled: true
      hosts:
        - "consul-1.${SECRET_DOMAIN}"
        - "consul-2.${SECRET_DOMAIN}"
        - "consul-3.${SECRET_DOMAIN}"
      
    ui: 
      enabled: true
      service:
        enabled: true
      ingress: 
        ingressClassName: "internal"
    