---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      # The main enabled/disabled setting.
      # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
      enabled: true
      # The prefix used for all resources created in the Helm chart.
      name: consul
      domain: "${SECRET_DOMAIN}"
      # The consul image version.
      image: hashicorp/consul:1.16.0
      # The name of the datacenter that the agents should register as.
      datacenter: "Helix-Ai-DC1"
      # Controls whether pod security policies are created for the Consul components
      # created by this chart. Refer to https://kubernetes.io/docs/concepts/policy/pod-security-policy/.
      enablePodSecurityPolicies: true
      # Enables ACLs across the cluster to secure access to data and APIs.
      acls:
        enabled: false
        # If true, automatically manage ACL tokens and policies for all Consul components.
        manageSystemACLs: true
      # Exposes Prometheus metrics for the Consul service mesh and sidecars.
      metrics:
        enabled: true
        # Enables Consul servers and clients metrics.
        enableAgentMetrics: true
        # Configures the retention time for metrics in Consul servers and clients.
        agentMetricsRetentionTime: "1m"
      # One of "debug", "info", "warn", or "error".
      logLevel: "info"
      logJSON: false
      tls: 
        caCert:
          secretName: helixaibot-com-production-tls
          secretKey: tls.crt
        caKey:
          secretName: helixaibot-com-production-tls
          secretKey: tls.key

    server: 
      replicas: 3
      bootstrapExpect: 3
      storage: 2Gi
      storageClass: "openebs-hostpath"

      exposeService:
        enabled: true
        type: "LoadBalancer"
      
    ui: 
      enabled: true
      service:
        enabled: true
      ingress: 
        ingressClassName: "internal"
        hosts:
          - host: "consul.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: "Prefix"
        tls: 
          - hosts:
              - host: "consul.${SECRET_DOMAIN}"
                paths:
                  - path: "/"
                    pathType: "Prefix"
            secretName: helixaibot-com-production-tls
    
    apiGateway:
      # Enables Consul on Kubernetes to manage the CRDs used for Gateway API.
      # Setting this to true will install the CRDs used for the Gateway API when Consul on Kubernetes is installed.
      # These CRDs can clash with existing Gateway API CRDs if they are already installed in your cluster.
      # If this setting is false, you will need to install the Gateway API CRDs manually.
      manageExternalCRDs: true

      # Enables Consul on Kubernets to manage only the non-standard CRDs used for Gateway API. If manageExternalCRDs is true
      # then all CRDs will be installed; otherwise, if manageNonStandardCRDs is true then only TCPRoute, GatewayClassConfig and MeshService
      # will be installed.
      manageNonStandardCRDs: false