---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  dependsOn:
    - name: consul-tls-cert
  interval: 30m
  chart:
    spec:
      chart: consul
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      # The main enabled/disabled setting.
      # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
      enabled: true
      # The prefix used for all resources created in the Helm chart.
      name: consul
      # The consul image version.
      image: hashicorp/consul:1.16.0
      # The name of the datacenter that the agents should register as.
      datacenter: "Helix-Ai-DC1"
      # Enables ACLs across the cluster to secure access to data and APIs.
      acls:
        enabled: false
        # If true, automatically manage ACL tokens and policies for all Consul components.
        manageSystemACLs: false
      # Exposes Prometheus metrics for the Consul service mesh and sidecars.
      metrics:
        enabled: true
        # Enables Consul servers and clients metrics.
        enableAgentMetrics: true
        # Configures the retention time for metrics in Consul servers and clients.
        agentMetricsRetentionTime: "1m"
      # One of "debug", "info", "warn", or "error".
      logLevel: "info"
      logJSON: false
      domain: "${SECRET_DOMAIN}"
    
    # Configures values that configure the Consul server cluster.
    server:
      enabled: true
      # The number of server agents to run. This determines the fault tolerance of the cluster.
      replicas: 3
      bootstrapExpect: 3
      storageClass: "openebs-hostpath"
      storageSize: "1Gi"

      serverCert:
        secretName: consul-tls-cert
        secretKey: tls.crt
        secretKeySecret: tls.key
    
    ui:
      enabled: true
      service:
        enabled: true
      ingress:
        hosts:
          - address: "consul.${SECRET_DOMAIN}"
        tls:
          - hosts:
            - "consul.${SECRET_DOMAIN}"
      # Enables displaying metrics in the Consul UI.
      metrics:
        enabled: true
        # The metrics provider specification.
        provider: "prometheus"
        # The URL of the prometheus metrics server.
        baseURL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090

    # Configures and installs the automatic Consul Connect sidecar injector.
    connectInject:
      # Enables metrics for Consul Connect sidecars.
      enabled: true
      # The number of deployment replicas.
      replicas: 2
      metrics:
        defaultEnabled: true
        defaultEnableMerging: true
