---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      # The main enabled/disabled setting.
      # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
      enabled: true
      # The prefix used for all resources created in the Helm chart.
      name: consul
      # The consul image version.
      image: hashicorp/consul:1.16.0
      # The name of the datacenter that the agents should register as.
      datacenter: "Helix-Ai-DC1"
      # Enables ACLs across the cluster to secure access to data and APIs.
      acls:
        # If true, automatically manage ACL tokens and policies for all Consul components.
        manageSystemACLs: true
      # Exposes Prometheus metrics for the Consul service mesh and sidecars.
      metrics:
        enabled: true
        # Enables Consul servers and clients metrics.
        enableAgentMetrics: true
        # Configures the retention time for metrics in Consul servers and clients.
        agentMetricsRetentionTime: "1m"
      # One of "debug", "info", "warn", or "error".
      logLevel: "info"
      logJSON: true
      domain: "${SECRET_DOMAIN}"
    
    # Configures values that configure the Consul server cluster.
    server:
      enabled: true
      # The number of server agents to run. This determines the fault tolerance of the cluster.
      replicas: 1
    
    ui:
      enabled: true
      # Enables displaying metrics in the Consul UI.
      metrics:
        enabled: true
        # The metrics provider specification.
        provider: "prometheus"
        # The URL of the prometheus metrics server.
        baseURL: http://prometheus-server.default.svc.cluster.local

    # Configures and installs the automatic Consul Connect sidecar injector.
    connectInject:
      enabled: true
        # Enables metrics for Consul Connect sidecars.
      metrics:
        defaultEnabled: true

    ingress:
      hosts:
        - address: "consul.${SECRET_DOMAIN}"
      tls:
        - hosts:
          - "consul.${SECRET_DOMAIN}"
