apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: consul
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
  # TODO: Fetch documentation link and add as a comment here
  # Working
    global:
      name: consul
      logLevel: info
      logJSON: false
      domain: ${SECRET_DOMAIN}
      image: docker.mirror.hashicorp.services/hashicorppreview/consul:1.18.0
      datacenter: helix-ai-dc1
      peering:
        enabled: false
      tls:
        caCert: 
          secretName: helixaibot-com-production-tls
          secretKey: tls.crt
        caKey:
          secretName: helixaibot-com-production-tls
          secretKey: tls.key
      acls:
        manageSystemACLs: true
        createReplicationToken: true

    # Working
    server:
      # Minimum number of servers required for quorum is 3
      # However inorder to avoid disruptions during upgrades, we need to have 5 servers
      replicas: 5
      bootstrapExpect: 5
      storageClass: openebs-hostpath
      storage: 10Gi

    # Working
    connectInject:
      enabled: false
      default: false # only want to inject when requested
      cni:
        enabled: false
        cniBinDir: "/opt/consul/cni/bin"
        cniNetDir: "/etc/consul/cni/net.d"
    
    # Working
    meshGateway:
      enabled: false
      replicas: 2
      wanAddress:
        source: Service

    # Working
    controller:
      enabled: true

    # Working
    ui:
      enabled: true
      service:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        pathType: Prefix
        hosts:
          - host: consul.${SECRET_DOMAIN}
            paths:
              - /
        tls:
          - hosts:
              - consul.${SECRET_DOMAIN}
            secretName: helixaibot-com-production-tls
