---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helix-ai-k8s-cluster
  namespace: flux-system
spec:
  interval: 30m
  url: "https://github.com/SinLess-Games-LLC/Helix-Ai-IaC.git"
  ref:
    branch: "master"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: helix-ai-k8s-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
