apiVersion: ENC[AES256_GCM,data:RtY=,iv:/ZwN2ss2eldjkL4oqd1LTODaOCXOOOZs++nMWHjZlsI=,tag:HmcljDSdpKteZkbeDbb9hA==,type:str]
kind: ENC[AES256_GCM,data:l7JQV+rF,iv:srZOLpi0h1+AQ4HV4ljcc6T41mjZ/2+LzmcHGIVFHOA=,tag:uh2d98K2+txOa6wCWak3Yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XPZEFHWkODe84XRWj7gN,iv:t43HZigOktM7J0f4W07BvC+8w4ObsBlT9r7CGyB1iro=,tag:NOGIuFTAzOMyJ6iCy7hxcg==,type:str]
    namespace: ENC[AES256_GCM,data:qetnI0yLDQLq8kA=,iv:sj3VBNnj0jFEbTe1VktSrZEu7CSkRmy4HB3cPy5+PKg=,tag:Wduergba0LK8XKx/KbSveQ==,type:str]
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ggJdVNVnY/pMCC6uziE=,iv:sbiLE6nOmhdCYAMFNUS38j3vQRwIws69zIuZe72QLm8=,tag:A2lL5eJqwnOJ4Li8zJiF0A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:TsfFkHBkQORnyVcWBEsl4dzlIRo=,iv:8l4cDCP6nd3lx+WxfLRnXVO6l93skb3/zF++QFW1V5A=,tag:sctFgOevas2T6WqJWycexA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ElM8jeRGf5uoDtqZNxLga+qQjjklBWJnMOq9UvJUV+hAu0+h,iv:DacufHBJJbm2nKUYuYFeM3k2rC3/TXjp6jufjzOU014=,tag:wWs0Ck40h1ciaf19slLQaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bjFxNDZ2bWJ1TCtRNTA4
            cjBjRHM4WDRpRkRTOCticDRJL08rQVNRZTBjCnhMWmJTNnlMVWRpWEtOOWxzdCty
            dlZRdm5objduWFNBeTlDa05ReWpBUWMKLS0tIGNRWjFldG8ybTdralRMRk5PRlVu
            ZzR6c1RsdE9tbkYwdUhNaFlhcTU4N0UKr4kXxS1UPGwXrffhDoAVhaQeo74SkokW
            9/s0TlP2Qsa+Bm3UXTZuOOdB6vi7Clx2PcK3VbDz/4FX1im3dvzTvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T23:12:33Z"
    mac: ENC[AES256_GCM,data:iLLHRBGVPO4Gfaa36Zd9jQ+qAVJKnBnP3Xu4pbtpP2hczRX62zjwp0tEPZX7A3yfysCVXbuzyHgh053V0oe4qlwd2g21mL9DVqeRAqzlwX48wJ3MkpQBQr1FOZB89QY//agbHKEMEbjbo9uYc+5ZDDtcqZu+QUfahs0njaeL7oI=,iv:MK9WCZkYDPn7i9xIvhGlXar18Amn7vqjkMeuKilWoOI=,tag:pwGOeRuG9nuDQG0J60YzLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
