apiVersion: ENC[AES256_GCM,data:fwg=,iv:eHgW01snivGUlQ7a2eKQvNUQEA/2Bbnps+ZhgPYOao0=,tag:aP3Cgz5iC9mXtb/FduHPXA==,type:str]
kind: ENC[AES256_GCM,data:N60QIupf,iv:hywgIU1N+yS4LoOHoo/HnWZ2CFgRkF7V1WCMpkMHL3U=,tag:D/sk3audCV/TWcOs6gBQXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BcTRBQh7RJpt9ZW6tGjS,iv:naOhCDisMheZNL1VdVOaCb288WxS5v5zObXkOWVGe24=,tag:XXh2+L4DjMOnxvtM85kDlA==,type:str]
    namespace: ENC[AES256_GCM,data:SyH6k6Jwbp21V9c=,iv:6f18PX2W4u5BXuO1iNZ8Z/ygylfp6JqmDqwvpMMHzPM=,tag:KzBYwbHO08U6BA6jMJTjiw==,type:str]
stringData:
    SECRET_DOMAIN1: ENC[AES256_GCM,data:nLPK/byjYZZo3lGLBh0=,iv:k6pI3DMrnzf6djzNhcXs7dD9wFpdAFh6ot533FHlf9c=,tag:0eQqC7WoGAYBku4YRRhTKg==,type:str]
    SECRET_ACME_EMAIL1: ENC[AES256_GCM,data:FhUVIQjRRkgF/Q8u7RW9SEj2aHM=,iv:WRgFE1orMM+m/BBiA0+jbvGk1BcutCZPbYq8EfcmjrY=,tag:CXzWUKc+yJkm8iUG/wHAbQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID1: ENC[AES256_GCM,data:zT1YsdDYsqduv6tkS8u8qhegoGXddAHIpeC1UHizr4p6tMJZ,iv:OLIunMzV6CoV+qptPjJMiRtqHPj/Mtwz0aS9QNDh21k=,tag:nwXC9X5qng/B57+ldJETvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age195rdta0e2jx49x3djpcchyc2gdslv3kdedsnzeu23xmtwremk93qpwvseu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEZ6M2NwWGJ3aDBkanho
            b0kzUHlSbERKZjRqbGVWV2J6TUx0NW1zdVZFCnJ2M00zNkp4T2liNEJYc29JMU51
            bHNLWjVBcWx5MzExZ2lxbWhmRU81Q0kKLS0tIHVPOTEreS9YeTZCcEo2bHAzanR0
            WGx3RGYycUNydm1sS1hCaUcrNGdGM1kKHC8/ClQPUv4rhdXmhyFEvLEBYdys4qI6
            WW5PpM4zINTwMvzQqHZGj/N6mUAPqTohsD451aLfAlucxp+QphOeWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T03:51:04Z"
    mac: ENC[AES256_GCM,data:DJO3V/e+O3VixAPKlpn529I8JJxj6M1NR8jCVbohLOCP/NTsXHwgaMQhSvUFrOeccJQ9ZpGQGrQ9xSXVWjPky8a8wOd/rMV0ZFGx8chZ6bN2bDFuXeonnKxOG5tL0P1lKp04WrgXi3+9KE9SLWFeo37ZF+iXLNJWLf1D/e3GpzU=,iv:3mobLdpNQezs5/CAEBR9K7yovJ09z2VcGffub489TCM=,tag:1Nvkwkygw5+zQVHpxBPjjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
