---
apiVersion: v1
kind: Namespace
metadata:
  name: data-plane
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
