apiVersion: ENC[AES256_GCM,data:lEQ=,iv:iGTxGBROKmBWkUBYFAJoZ6RReAQzL7S43lWLsXyjg58=,tag:bVDt1w4glAkk5/Tn60oTKA==,type:str]
kind: ENC[AES256_GCM,data:UGb5lRXC,iv:mZHJvrjdF9izRAvKtBsWwW+vEjapHWX3lLnlQVL2Dvs=,tag:rrMW98zMOaEdzylVde+D4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:81x9fvHjtAQjPOy8+PUSGd5EesCtDbRcYLA4,iv:et1ZFb3AAPpjgsKqI1bQ7eYHR6ZEynKEpKEL4vG2Ij8=,tag:yHR2WtNoUEAbi4Y0A15Hwg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:YJw6vV20PbE43hT3BcBAqmGB1+Z7qcr+omJTNMvL1nq8iihsGDsAiXUtaydiTdJAskTRZ2XRvWpXMATe9jzui1COSm/zvqh5KtNNkVSYNwXalEX9q6YnMxHc7pCmmvtMEGswBvlnu0YtdEc9n/Ss0iIz7hXEKv3Y+Q==,iv:7Wx+OWVe95FQIx6um9mbex9FIriRDWVaE6c2Lrqgvjw=,tag:DQnAUP0zPpJqpMJtEd6lDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSjlDY1gzWS93SXhlc3RY
            VTI5V1hyTHhFTWhja0ppaHAvd2hmRDE4LzJJClFSRTFFcGZMWTFwYVJFVEJobktl
            MzNjTVVKUmtKNmhNTTIvZHBUbUZpWXcKLS0tIE5ReEozOS8zSElsejd2VkRycFR5
            S2owdnZNMjNDMHU2UWNEVmNlSm5VcmMKE2K/5KXd5YFK8Y64h1FGmp5V04JowiDe
            D9GUL8Zd57q0vFwrue8vETSCV4GIASrsaNaY8FAqgyIOUE+sLCgG7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T02:59:03Z"
    mac: ENC[AES256_GCM,data:eH/r8sNai7Y7PnPBPRbKuoBEeaDthFzKUWg5SOEyTto3jre5gVIhNslXZ1TRnj1Y/tQ41atBC51CtXvNzXMRSgEl0tDw5OeUcROydD3CygbSCb3/f2sL9KZWTN7Dvnpr18DS/LZmG6Tv9JfvSRa190CAVmN+9fkd9zxw3mTVJhc=,iv:DgwJpu4oH7/9H9wQaQFMcfw9Ew8YbUl9cK3nG4yg9Bs=,tag:MH/U99bmtDKKn+XQIFi5Lg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
