apiVersion: ENC[AES256_GCM,data:nlI=,iv:amAtkQ5aaKdy3s89Xp9WRxKtVuY36v1HrntdMwtxqXg=,tag:UQr/ZgkjWAqo/4aEMd2BWA==,type:str]
kind: ENC[AES256_GCM,data:RfvuYYE7,iv:i5gZ//5BIM5D1pscrdb8m2vG4Oj+ZOUUPNo1sjE6amQ=,tag:ahP04v1JYnA3Lkdmy6dxng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M5pZkGzO0zNloSNma6dCcWTTr2JJDW/syia+,iv:6+278x6UPKy5e7Pfn6t5RHFqbAx0cTiG87eZClqAkeA=,tag:PzMuSzhbOUKJZHi+TrgxPw==,type:str]
    namespace: ENC[AES256_GCM,data:6LFPfNZE7Sw2ny8=,iv:H9xa5uqeS5LsWjosE9F1pR9QjGfPj0FKzJ+FdjpmHho=,tag:Ge3feZJCveGl0aGMMmWpog==,type:str]
stringData:
    token: ENC[AES256_GCM,data:wfArsoSJjtPxVJZjMQaMJ5TpTqzjxlta5ArclFOweuU2+K/6o6gHXHJRzyJwKkdLPaV6sIkmc57HzCqoJrMP4CYIf0Mjj+Gg/8r1UgL2Coipej7VG5rgrIhJbFWfIfI1J6S8MjO5daA/S7Ow1SH3KkFdp5V/nlU3gA==,iv:wR6V/LxKBR6voQFktvso9AswWj2b9O98gwpmSUmEimA=,tag:LL3V+sCfCplpAyUuar+vSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnekJzMlBQUTFtOGdSZ1FV
            WFU2ZmhMSm5ZZmluc0EvcHRza09JaDZ3ZUQ0ClVkREw3UnZEcWRhQ0tSTWhIV1ZZ
            cHJYakd4NzN6ODZ0cUN2amtsQWw2OVkKLS0tIHlVczZDdnVENEgxSHM3N1ZsVEdL
            dThoM0tyZkdpU0hqb3laWWNYL3oyancKpa+1k8fFEhO842/TZScPB31V4r5pCnlf
            5mvyqVQws4pd6gvQ5uQLj9tVgNz30ygAh1JporBRAI3AjyxT4qheSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T23:12:33Z"
    mac: ENC[AES256_GCM,data:0zxPNGQuuMcu+kHu/tcU9Rk56XR5I8MYbSDMpmcZOtioL4tr1HTvf5fhPoy1VsQVU4k7HcMJpvlhq8eB9ghMDLEU+UDZMVT7m+3C/PtRaANgJIR1muhcHj/dfNoBl742c2IfH4/rjTQ2awOxKIMBIrM4ekqbHxbeIkHiyXI18Jk=,iv:dq0avZiyhknMsCa1JDIAh3oNpeNiGOVI9xn8GJZ4VTU=,tag:FIYbW0s0R/WsRuNsZYTYzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
