apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: data-plane
spec:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  # secretName: redis-secret
  # secretKey: redis-password

  redisExporter:
    enabled: true
  
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
            storageClassName: openebs-hostpath