apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: data-plane
spec:
  clusterSize: 3
  clusterVersion: v7
  persistenceEnabled: true
  # secretName: redis-secret
  # secretKey: redis-password
  
  externalService:
    enabled: true
    serviceType: LoadBalancer

  serviceMonitor:
    enabled: true
  
  redisExporter:
    enabled: true
  
  storageSpec:
    storageClassName: openebs-hostpath
    storageSize: 1Gi
    accessMode: ReadWriteOnce