---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-oncall
  namespace: monitoring
spec:
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 30m
  chart:
    spec:
      version: 1.3.106
      chart: oncall
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    base_url: oncall.${SECRET_DOMAIN}
    base_url_protocol: https

    engine:
      replicaCount: 1
    
    celery:
      replicaCount: 1
    
    service:
      enabled: true

    #TODO: Figure out why the ingress defaults to example.com
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal
        cert-manager.io/issuer: letsencrypt-production
      className: internal 
      tls: 
        - hosts:
            - "{{ .Values.base_url }}"
          secretName: helixaibot-com-production-tls
    
    database:
      # can be either mysql or postgresql
      type: mysql
    
    # TODO: switch oncall to use individually managed MySQL instance
    # externalMysql:
    
    # TODO: switch oncall to use individually managed RabbitMQ instance
    # externalRabbitmq:
    
    broker:
      type: rabbitmq

    grafana: 
      enabled: false

    cert-manager:
      enabled: false
    
    mariadb:
      enabled: true
      auth:
        database: oncall
        existingSecret: mysql-credentials
    
    redis:
      enabled: true
      auth:
        existingSecret: redis-cluster-secret
        existingSecretPasswordKey: password
    
    rabbitmq:
      enabled: true
      auth:
        username: rabbit-admin
        existingPasswordSecret: rabbitmq-credentials
 
    ingress-nginx:
      enabled: false

    externalGrafana:
      url: grafana.${SECRET_DOMAIN}