apiVersion: ENC[AES256_GCM,data:jnE=,iv:8BRHl/RG9xu1eSi+noylEqTTg5dyZ23kgkgGA0hyXqY=,tag:NjU8mUQXmbBi6ZT6ojz++w==,type:str]
kind: ENC[AES256_GCM,data:A42r+pi9,iv:n9DWr9WCaPnVv4xpsuyQDEf2xZSdvGONuoo4XRveS+g=,tag:MSPfmawRYjDI8KrVxhfZGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5sYWj3LS5vVDInHVTeLGx5P2/TM=,iv:2G53zckbUOlF5RfY5b/+r43mneCYCkNBwn9l56gqKN0=,tag:BZYNVGlkFlpFShwdEHUF6A==,type:str]
    namespace: ENC[AES256_GCM,data:nfZ1vL9cU8BYFw==,iv:C0YvD+IVZvLG6dCFDc5WsJWM+PBNjydB8buxoQdNsRQ=,tag:eJJyv4Ow6MiQnzLl0Pu5mw==,type:str]
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:ksmiC0DEaMbIg9+6YVNC3t5/8ASN,iv:BL9G4wkkx8AjA3PqIMHdwEM40Wkw9D95cupf5pkUvYw=,tag:onw/uiDRLoD6oyPySMR0AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TW5nakhCWXF2MllDeGxj
            L3BTU25XVnZHZG9yWkltTnQ1SzlGS2hvZVQ4Cmo4ZlNsbVBGak03b2J0Tm83ZURh
            WGo2ODVSTDJXNG5VdzZHaUUrbW9FcHcKLS0tIEtkMWJFYWUvbEFhZXlyTzVJSUt3
            VnVmM0luVVpJZzR2NldNdTZlWnpZZmsK+c28/IotdGU3rqDeTPglaQ9yq3sYh2Kw
            CRi6Z+CsKiKKdTOWidqJOjOLAdrO22sxlmrbzwXc14ECDzVChXYzbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T04:44:00Z"
    mac: ENC[AES256_GCM,data:dJ3XLOyDqjy4a1Lg6+9egp/VoCEUEBL2egsvWsmJcoUcX0yueZbR52TFI88vaa/UlxvikcM45kRKtDWebi+WBwM+uPjurNJCAt5CQAs/jnHcf9XgriR11mm9f3DiGilyG7rFkw2H7VHEWrbidz+Csze8TuBVJL74O3tfy1Y4NOA=,iv:dLYUdD7Pz1w4Oqeo+2dZ2ArawTcwHZXg3vOIbcKQaMU=,tag:CgEAT2NXmu2/chKsjRHG+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
---
apiVersion: ENC[AES256_GCM,data:jnE=,iv:8BRHl/RG9xu1eSi+noylEqTTg5dyZ23kgkgGA0hyXqY=,tag:NjU8mUQXmbBi6ZT6ojz++w==,type:str]
kind: ENC[AES256_GCM,data:A42r+pi9,iv:n9DWr9WCaPnVv4xpsuyQDEf2xZSdvGONuoo4XRveS+g=,tag:MSPfmawRYjDI8KrVxhfZGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QEdD2zWKTvw4s7eNxBsMKLaZR/iuBvs=,iv:dECHWXqH/dmvFq/Md1dCEk0xxbWeHPIs1npYgJYK7k0=,tag:yIECs03ufPW4THo3LD8EdQ==,type:str]
    namespace: ENC[AES256_GCM,data:nfZ1vL9cU8BYFw==,iv:C0YvD+IVZvLG6dCFDc5WsJWM+PBNjydB8buxoQdNsRQ=,tag:eJJyv4Ow6MiQnzLl0Pu5mw==,type:str]
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:O2G1AqSlX4SHHH5OEtC5WtjTG7M9tfDdZw6SMt88qIDM5syPSaGnsWtJAn8UxxGc,iv:omEbyoofMrZvY50nnRKb8PpVa0EG8hTg9G/Aj5Dgr8I=,tag:LafguGkQaP9bf/NNi4BSRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TW5nakhCWXF2MllDeGxj
            L3BTU25XVnZHZG9yWkltTnQ1SzlGS2hvZVQ4Cmo4ZlNsbVBGak03b2J0Tm83ZURh
            WGo2ODVSTDJXNG5VdzZHaUUrbW9FcHcKLS0tIEtkMWJFYWUvbEFhZXlyTzVJSUt3
            VnVmM0luVVpJZzR2NldNdTZlWnpZZmsK+c28/IotdGU3rqDeTPglaQ9yq3sYh2Kw
            CRi6Z+CsKiKKdTOWidqJOjOLAdrO22sxlmrbzwXc14ECDzVChXYzbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T04:44:00Z"
    mac: ENC[AES256_GCM,data:dJ3XLOyDqjy4a1Lg6+9egp/VoCEUEBL2egsvWsmJcoUcX0yueZbR52TFI88vaa/UlxvikcM45kRKtDWebi+WBwM+uPjurNJCAt5CQAs/jnHcf9XgriR11mm9f3DiGilyG7rFkw2H7VHEWrbidz+Csze8TuBVJL74O3tfy1Y4NOA=,iv:dLYUdD7Pz1w4Oqeo+2dZ2ArawTcwHZXg3vOIbcKQaMU=,tag:CgEAT2NXmu2/chKsjRHG+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
