apiVersion: ENC[AES256_GCM,data:jnE=,iv:8BRHl/RG9xu1eSi+noylEqTTg5dyZ23kgkgGA0hyXqY=,tag:NjU8mUQXmbBi6ZT6ojz++w==,type:str]
kind: ENC[AES256_GCM,data:A42r+pi9,iv:n9DWr9WCaPnVv4xpsuyQDEf2xZSdvGONuoo4XRveS+g=,tag:MSPfmawRYjDI8KrVxhfZGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5sYWj3LS5vVDInHVTeLGx5P2/TM=,iv:2G53zckbUOlF5RfY5b/+r43mneCYCkNBwn9l56gqKN0=,tag:BZYNVGlkFlpFShwdEHUF6A==,type:str]
    namespace: ENC[AES256_GCM,data:nfZ1vL9cU8BYFw==,iv:C0YvD+IVZvLG6dCFDc5WsJWM+PBNjydB8buxoQdNsRQ=,tag:eJJyv4Ow6MiQnzLl0Pu5mw==,type:str]
stringData:
    user: ENC[AES256_GCM,data:ldMCAFaQiyKrdZVc,iv:LTWERPxUVFcdBwC6PP0BHgPULIOD5PUQMwIRyQY5h5U=,tag:nUwgoammKLMvN4NaDD/7mg==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:ksmiC0DEaMbIg9+6YVNC3t5/8ASN,iv:BL9G4wkkx8AjA3PqIMHdwEM40Wkw9D95cupf5pkUvYw=,tag:onw/uiDRLoD6oyPySMR0AA==,type:str]
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:N0J53IukM2zy5ZP4WTUMMHNGe5ERGNNF,iv:fMFboLiiHbu0ICAOcQmMgWUjjPq+WzV7O9rZsilhYOo=,tag:1Cip4P5E2bbeBFFrOIoLeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TW5nakhCWXF2MllDeGxj
            L3BTU25XVnZHZG9yWkltTnQ1SzlGS2hvZVQ4Cmo4ZlNsbVBGak03b2J0Tm83ZURh
            WGo2ODVSTDJXNG5VdzZHaUUrbW9FcHcKLS0tIEtkMWJFYWUvbEFhZXlyTzVJSUt3
            VnVmM0luVVpJZzR2NldNdTZlWnpZZmsK+c28/IotdGU3rqDeTPglaQ9yq3sYh2Kw
            CRi6Z+CsKiKKdTOWidqJOjOLAdrO22sxlmrbzwXc14ECDzVChXYzbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T04:24:17Z"
    mac: ENC[AES256_GCM,data:II85fKADlPFk90qFFED6VZASiJjYY3LKz/kzUMm+65sg99BC22Ot9Q5J8BRsxoEDkl0mFTGsWdwpuIGlMlWl1vjwu0ZmcUxijNhlSsxXuhOrWbERykp4wQJ/FJ138cmwjGUHaeNkHF6XeR6Ihq/4DvcyvrmQ1iXJy8q/wcp5ITA=,iv:Z9fjO1juU1GOSuSf5jQxoCF3e4JxKVGIB5KbbeQ4/8s=,tag:4l/+n1Gf3mwWX6wTRoQM3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
