apiVersion: ENC[AES256_GCM,data:bWY=,iv:vuLuhSNcZ/LMLOWJaiLAvuqaG2lFEZKKz6zxxkaitwQ=,tag:AQzASNGlwJnQaYBae8/olQ==,type:str]
kind: ENC[AES256_GCM,data:d++Wvl61,iv:YIM3mnEwYytcJpxBpLT9WyxFf8zuPX/CbJ/Iy0UsIBk=,tag:PAfLv+WO+DzZdJmmnFL98w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CNHZUnksXHK4jKRouEOO1uc=,iv:TQSHYMphmOR0D2GDBdxMwlxcK+7PQaLKazeLGLGBEuI=,tag:oVj5hU38EeVKgvkFQ1lM2g==,type:str]
    namespace: ENC[AES256_GCM,data:wScnmnGgxZLTrA==,iv:ujNpUW4K3o7G82Duv+fk+mcr+E7RdjGvmLriqFasbgE=,tag:nqqkzhq1Q6WMDU/iqdPCnw==,type:str]
stringData:
    user: ENC[AES256_GCM,data:vnNNwVrC5wQxxOYr9jc=,iv:o1CMW+WnVx299v08f0yHP8N8iVXoNzxg/MINkrNh6GA=,tag:6ZHzyk6yMZyBruP+3GQB5A==,type:str]
    password: ENC[AES256_GCM,data:V0Z5NOvPX03eiYbP0WjjvXSeSqOrPx2ndSfD/Ku5UhMychSUTRtFUg==,iv:+GW4ZycCN+Awfp/44ZniSZ19XMVZz1eSEg71fNbzuf8=,tag:mUvA5uvSOLS27KT7WkxvVQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:8Yhn+6Ae8gOjPW4NWXViK8nJ9Z5NJf0tHOXaQuKxuCuzJJ7Zo2G0VfmEZA==,iv:acNEWav7r84m6CeM4DplB21Y8K0r2B6PfbIrNPs587o=,tag:4jGC/tnBna1VGOZ368yukA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjMveXlBK3o4bzNndGxJ
            ZkpZNzc3ME4yYkptdFlUOCtrbXBlR08relY4CjZLOXY2NCtndlQxTE9GTTR6cnM5
            YlBXQVk3ZzNyZ1l3ZzNQMk5NNm0zc1EKLS0tIGNsMWRFazFOWGd5OFlqWWFUMVZ1
            WEJobHBtZDkrS3FCSG8xVUQ4Z1JKSkUKC4xn05iSiJKROqAngIMJzEQy515z0uWe
            cN13YImfZWiTOArPwqRaKjgZuDVZz+LVUPL1eZyQ190fRb1bB+WvCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T00:15:30Z"
    mac: ENC[AES256_GCM,data:UZtlO+T9qxVItUTnLGK2qse2rSUmkKOFsbYotx4Vim1Ky3/wmfJwNQb8nQcoRl9Vl65Sc1uNIREz/ZHtqB8Bps4b/l81BYES4jqfk1WKlsKw7lWBm+YXmKgIbapjdeS5nXoUyb1rKPyvzYko+EY8y+cZoUIsXz/He6Oj3nf+Lhc=,iv:tqkv+jDwqpR34csG71iha4yWifaPzooNM2JkoQwR6Lk=,tag:LJES/8x6frlxcIy9jPgM7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
