    apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: pdb-rabbitmq
      namespace: data-plane
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          app: rabbitmq-cluster