apiVersion: ENC[AES256_GCM,data:BGo=,iv:s5bDqQtS1VRsqJEreUd/N3yTLk9yniqE4WL/mFzeuQg=,tag:zKKZYcffeO7ouRtjTDEz4g==,type:str]
kind: ENC[AES256_GCM,data:YwSio2y2,iv:XR5UQiLQ9KRjN7N5Hk6fQ/u0cQqSl5/E8mHgYc3lh+g=,tag:3ZAO4zIIdoZXQj9m9X7NuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YphA9PKFTg26JFQL+5CY4PbyA0nL,iv:Xfgqp+bl+xr0+UciaL6/ctSPEC8l6iGul9HGJtlFkYY=,tag:ptPCYf3X2eiU7CLlkyT5ag==,type:str]
    namespace: ENC[AES256_GCM,data:+Dg6rEvf2YdF1w==,iv:yxOPsa5fIgTmKMNb+5m3Kk+jNFr8DmIk324+FtWM+GU=,tag:oqBqiiw8baA8mHkkOsbCUA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:f0oHwTP94M25AmfT,iv:HY5YKqpmysjSYZF69hlmbY1H+iZ/8yeva6SqI1QorJE=,tag:HbCza+zteFd52LMYgljysg==,type:str]
    password: ENC[AES256_GCM,data:ghUO0SPDTdv+E+mn45H5tV61NthZ,iv:9WB8BRhjFVCsBlU0qRPuQt7jMrCP2si/71M9bOyMraQ=,tag:coDfoqLh1ejk02/M/WiWxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NG9hQ1Fhd3FjV1g0bzVj
            RndmNGs2RXZOTlFsV09UZ2pQT0h3N0FKNVNJCitvZTRTVmhIS3l4QXJvbWQxMlNi
            cktybzd6M3RIaFQvbDBZQ05JMVJKVDAKLS0tIG05Q2d1d1F3R1ZWV3gvNU9FM2h6
            akk2TllTWno2R1ZVTTZWN2tBTlhJbWMKp2bkLtjNt3EVpKJe8/isJCIOaEqezO7m
            JpCvWcAd8IZmBDT3uP81IFxkJwrcygiXqkfzm6nXNmMHdSiqY3Hciw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T22:10:30Z"
    mac: ENC[AES256_GCM,data:vaEYPKdgO6lpzn9xMETncbaxylUY7xIYAj8J/SCnbX3tzcGmCGe7u3RDvRUPXfkSTZpiu0nMdpLQLwBINyDfrl69QjRpUAh5dRsm7R7E3KoWRmGyjE8ukO75TrdU6s+CO5BWNLtvChmZUJifE4TyCpUiBWUmlX8lG33N4lbk10g=,iv:K6+VYNuPwTMwyqrr/rUKjWCJ8abVbszDdoE6p0EqNW8=,tag:JN3L+HwLtNk4FUHyPMdprg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
