apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-admin
  namespace: data-plane
spec:
  rabbitmqClusterReference:
    namespace: data-plane
    name: rabbitmq-cluster
  
  tags:
    - policymaker
    - monitoring
    - management
    - administrator
  
  importCredentialsSecret:
    secretName: rabbitmq-admin-secret