apiVersion: ENC[AES256_GCM,data:5tw=,iv:W7xvsMLl+BYmBmK69deAo6TdeLM/Jft3YnWsq35sFz8=,tag:XvxMlnmR084uk3EOawHi7w==,type:str]
kind: ENC[AES256_GCM,data:VcDfo/1Z,iv:nEBIWFv5M+avxqn6YP1QGKsDuuLuVev0NoM/vcYjkeg=,tag:uHbjuzrqVak/rLxH6OESFg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:Khomcx6qp7nTmwJc4WCqolYRDg==,iv:CYKwwQxmDcrTipr39CIxW8IEJ4eG/mFVTR1fiaQJaW8=,tag:l2LjCH4qfIc6xKp+rbkByg==,type:str]
stringData:
  api-token: ENC[AES256_GCM,data:NPYwT7WeCYjsuVM0E+IqcTZwTdo/3j8hyVVUbQzStXbGRYUAqi15RQ==,iv:S7pQ+xEcFjwMXSuhdVcJeq9pNiFlu+L0JQc2pqTWYlU=,tag:2+ZgHjYTvDDedOGuZXwyyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age195rdta0e2jx49x3djpcchyc2gdslv3kdedsnzeu23xmtwremk93qpwvseu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SFB3cFRnNm5mdmhRQThn
        OUthSDdHU3NqaVRCYkRsTjVDYlQvQUpUZ21zCnNtWVBZNXZxb05TS2VITzlybkMx
        MWJLdGZ5KzJqeExiMGQreWJHL0xjSncKLS0tIHhnVUlOT2wrZ3NBYlVaYUJtc3Ix
        T3JBUWRTT09HNzRMZGpoamtSZS8rUmMKPBgAaA2k8F4pq9HLDsNw4D5lC3JLFNns
        CVicxjhKrUgnbssDCA9mUXURQ0utLx4nNwrAw/jvzT2ObTKMmYfwAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-02-07T04:08:38Z'
  mac: ENC[AES256_GCM,data:fstuXCeEbhnND4s/X0h5s/uNhm6+afKDsjTA2OED1/mJq1yWr9YY1/sWg8rMOW8Cqzbfs/K7hVxpzoOWWu0zLZIWN9dBoW9oLxJDMQqvGyWjXwUYXDBdzKurirONFAAfAsta2+4HjV/4nJ/kyBuZyNQcL4sc3rLcqisJlK/hvQE=,iv:gHbbTBARG+uTo1Ukp+ZFMpWXVc08L5kecTHuR9kTYRk=,tag:CgWwQZPHLsXqil/z1xu4Gg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
