apiVersion: ENC[AES256_GCM,data:NmY=,iv:BN1apo/9oToUd0WJJK+L1SloX82oJzJoZlF+KkDu6iM=,tag:x1SYCiRx+ZAovcWst1Eg0Q==,type:str]
kind: ENC[AES256_GCM,data:inMpGHUH,iv:dEVP+uqRizR0uARgTkXXd29meBJSLhRtciiu/QQHXP0=,tag:pFciMEU4TkajWPKUgKockw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ljh5tQW6lzpRX5Yq64vJfSRehA==,iv:KwO+LwKOttkdfquHcbNV9YNaisrOyH+n/Kc0yjFjiWg=,tag:/qZkMMhqzuK2dAlLY4agTA==,type:str]
    namespace: ENC[AES256_GCM,data:ImB7or5VGg==,iv:+vEPV7r2bec29tLFKbV+YjyejJcYxzyd5srnm9dRhdc=,tag:md2NmCFV1Dh7OKyZs+sD/w==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:tKgNP3+7ijicu4I03M4lWm3DyJJhP/7/q21FauktYhv28CPU60jN3Q==,iv:PHejkE5qpjOqe4uqTqRQeel7GK22ixDm67i3eGc+3Yg=,tag:UHb1ER6OV3/S0RPyaF1SCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOGZVVkJERFdaMGRRam1S
            clhrVDdtbXgxOVhUdTlDSXdpWjBISFd3R2tvCnVhaTVNRTlUMGNwMVVLQ1Q1SFdt
            S1ZtTm0rOWxybEZ3cXpRQnY0VzBVdzgKLS0tIEt3dGJJZUV0M2R1NmhFR2lCL1Ft
            OXdlTW56NTFjc0hNVmp0T0RzQ0JWYkkK3yXU+h2lPveZ4XpGpqTPsy708BMdWTqS
            gaTSpFrexvBBCVStpNhVh0BZy5226J5W92jcRA8h4JBfuryhcM0WQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T00:14:06Z"
    mac: ENC[AES256_GCM,data:3ppgfCaQTHPIm0WnsKUedh+FMz4zfQmJs84T3rf1zI3myc1rjshRdXancjYAp9c3iw+IyH1lcrIRCKUryN7kfnVsVJrce1Hb2/h/n3rA85lNV9/8sqr1o1FbEmBv6KXks1ZP+AbttNzsJKZFJ9cbt9TrdwKTjcJblrGQ484jDfs=,iv:w3fIywqICYs9c23+FWtRKFfrRxwpik+QOhjHjQOmFvs=,tag:oAaG9dpyC57jL8WREaC/DQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
