apiVersion: ENC[AES256_GCM,data:nCM=,iv:Vqf144wnLZWf16kc2NSVXlCVpU5LT7qKWixvh/bN/hQ=,tag:VW6G1M8KsnXYDYQNewV8hw==,type:str]
kind: ENC[AES256_GCM,data:Qy62AMzn,iv:ribgN9/hPQHGLWFc5Xy2111iABumIp/aCYzKQiwX2Ok=,tag:lDBAvHj5G0deL8jqkO7jBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wrLOUXZ1z08aeyE538a0MWefWw==,iv:TbsmKfbi5nX9uDslYZQQFPm8hsswtiBUIDXY6Saj5ME=,tag:qgk94wp2XJgu5BbVt44ILA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:UqmHYp2310PXnsqvfsw2BLm58GBVieNnzuYDoAPKPjzT2HDF13FNpg==,iv:7p1/Y4UMOReL4uUDDXCjO1xS4ufOBQ0PMOD0ofCz07g=,tag:6vHdDzvfZim0L2q+gzOytg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5z0jtt8kxkpwafq2sjcwdq9y3ljct9xhc2r6kz2v20vn5c4vddqzdjuq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNGdBU0JCRFh0K252cjF5
            ZEJkTU0xMGczenpLcnU4cENoU2cyakZVVndFCkllc1VRQkpsV2VibXgvYno0bVdP
            aWYxSTVEalBQRm5HTllMS3NTbWFIdmcKLS0tIGg4anNIc3ErRTFTMEpHT3pPdzR3
            UW5OVjVCckd0Vms1MU01SnNNU3dTY1UK9QjQUxt1kMZ6fQynHSK5/GzMYMZVziyz
            zm2XCly/gOUMJ+Cc+wRgyJwDWvtHiDMiSCOURaX6CtnoZYvPdhjvwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T05:23:50Z"
    mac: ENC[AES256_GCM,data:Z1BwZFMpEwtzVuWyuahEhoXBG2fH1uIuMkFfPgQR6+87P8PnoD7qPStIyC7kU6sWJjuKzjRTPVBiGz/+EbfzZqCD/cj6c/mPCrv20DYW+DSJu/g5Sw/DBYp0ptS07MHi2YnUpBrez6zmIInF5V+nwOQPYDeC6sVgR5yOHCVdPU0=,iv:gY2h23e9TZGw6xnFebANpwnTNrC+W++pfKY5ihpTbVg=,tag:EVNsqRcB6wm0OrSJEr3EnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
