- name: Packages
  block:
    - name: Packages | Install [This will Take a while to complete]
      ansible.builtin.apt:
        name: '{{ packages }}'
        state: present
        update_cache: true
      # loop: "{{ packages }}"
      vars:
        packages:
          # Base Requirements
          - apt-transport-https
          - ca-certificates
          - conntrack
          - curl
          - dirmngr
          - gdisk
          - gnupg
          - hdparm
          - htop
          - iptables
          - iputils-ping
          - ipvsadm
          - libseccomp2
          - lm-sensors
          - net-tools
          - nfs-common
          - nvme-cli
          - open-iscsi
          - parted
          - psmisc
          - python3
          - python3-apt
          - python3-kubernetes
          - python3-yaml
          - smartmontools
          - socat
          - software-properties-common
          - unzip
          - util-linux
          # User Added
          - make
          - automake
          - autoconf
          - genisoimage
