---
- name: Get absolute path to this Git repository # noqa: command-instead-of-module
  ansible.builtin.command: git rev-parse --show-toplevel
  delegate_to: localhost
  become: false
  run_once: true
  register: repository_path
  changed_when: false
  check_mode: false
  failed_when: repository_path.rc != 0

- name: Copy kubeconfig to the project directory
  when: k3s_primary_control_node and production_cluster == true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/tmp/production-kubeconfig"
    flat: true
  register: prod_config

- name: Copy kubeconfig to the project directory
  when: k3s_primary_control_node and production_cluster == false
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/tmp/staging-kubeconfig"
    flat: true
  register: staging_config

- name: Print Both Configs
  ansible.builtin.debug:
    msg: "{{ configs }}"
  vars:
    configs: 
      - prod_config
      - staging_config




# - name: Update kubeconfig with the correct load balancer address
#   delegate_to: localhost
#   become: false
#   run_once: true
#   ansible.builtin.replace:
#     path: "{{ repository_path.stdout }}/kubeconfig"
#     regexp: https://127.0.0.1:6443
#     replace: "https://{{ k3s_registration_address }}:6443"
