apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/release-name: istiod
    helm.sh/release-namespace: istio-system
data:
  mesh: |
    enableTracing: true
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: 
    defaultProviders:
      metrics:
        - prometheus
      tracing:
        - zipkin
    extentionProvider:
      zipkin:
        service:
        port: 
      prometheus:
        service: prometheus.monitoring.svc:9090
        port: 9090
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    ingressClass: internal

  meshNetworks: |
    networks:
      production:
        endpoints: ["production/*"]
      testing:
        endpoints: ["testing/*"]
      staging:
        endpoints: ["staging/*"]
      data-plane:
        endpoints: ["data-plane/*"]
      monitoring:
        endpoints: ["monitoring/*"]