apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |
    enableTracing: true
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        datadog:
          address: datadog-agent.istio-system.svc:8126
    defaultProviders:
      metrics:
        - prometheus
      tracing:
        - datadog
    extentionProvider:
      datadog:
        service:
        port: 
      prometheus:
        service: prometheus.monitoring.svc:9090
        port: 9090
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    ingressClass: internal

  meshNetworks: |
    networks: {}